(()=>{'use strict';
const K='abyx_lang',S=['en','fr','it','de','pl','ru','uk'];
const DATA={
en:{questTitle:'TEMPLE QUESTS',questSub:'Access, choose and launch your temple missions.',steps:[
['Open the Temple Quest menu','Tap the <strong>Temple Quest icon</strong> on the left side of the world map to open the mission menu.'],
['Choose a temple and tap GO','Select one of the available temples, review its mission, then tap <strong>GO</strong> to open it.'],
['Choose your mission options','Use <strong>Free Refresh</strong> to change the mission. The first 2 refreshes are free; later refreshes cost Rubies.<br><br>Use the <strong>upgrade button</strong> next to the mission rank to improve it to <strong>A or S</strong> for better quality and rewards.']
],buffTitle:'TEMPLE ATTRIBUTE BUFFS',buffSub:'Each temple grants a specific seasonal bonus. All temples also increase Ruins Affinity.',buffs:{
shou:['Season Warrior Defense','+15%','Increased Ruins Affinity','+15%'],seth:['Season Warrior Attack','+15%','Increased Ruins Affinity','+15%'],nout:['Season Archer Attack','+15%','Increased Ruins Affinity','+15%'],tefnout:['Season Archer Defense','+15%','Increased Ruins Affinity','+15%'],geb:['Season Cavalry Defense','+15%','Increased Ruins Affinity','+15%'],nephthys:['Season Cavalry Attack','+15%','Increased Ruins Affinity','+15%'],sobek:['Reduced damage to seasonal troops','+5%','Treatment speed','+50%','Increased Ruins Affinity','+15%'],isis:['Increased Hospital capacity','+500','Treatment speed','+50%','Increased Ruins Affinity','+15%']},prefix:'Temple of'},
fr:{questTitle:'MISSIONS DES TEMPLES',questSub:'Accéder, choisir et lancer tes missions de temple.',steps:[
['Ouvrir le menu des missions','Appuie sur l’<strong>icône des missions de temple</strong> à gauche de la carte du monde pour ouvrir le menu.'],
['Choisir un temple puis appuyer sur GO','Sélectionne l’un des temples disponibles, vérifie sa mission puis appuie sur <strong>GO</strong> pour l’ouvrir.'],
['Choisir les options de mission','Utilise <strong>Free Refresh</strong> pour changer de mission. Les 2 premières actualisations sont gratuites ; les suivantes coûtent des Rubis.<br><br>Utilise le <strong>bouton d’amélioration</strong> près du rang de mission pour la passer en <strong>A ou S</strong> et obtenir de meilleures récompenses.']
],buffTitle:'BONUS DES TEMPLES',buffSub:'Chaque temple accorde un bonus saisonnier spécifique. Tous augmentent également l’Affinité des Ruines.',buffs:{
shou:['Défense des Warriors de saison','+15%','Affinité des Ruines augmentée','+15%'],seth:['Attaque des Warriors de saison','+15%','Affinité des Ruines augmentée','+15%'],nout:['Attaque des Archers de saison','+15%','Affinité des Ruines augmentée','+15%'],tefnout:['Défense des Archers de saison','+15%','Affinité des Ruines augmentée','+15%'],geb:['Défense de la Cavalerie de saison','+15%','Affinité des Ruines augmentée','+15%'],nephthys:['Attaque de la Cavalerie de saison','+15%','Affinité des Ruines augmentée','+15%'],sobek:['Dégâts subis par les troupes saisonnières réduits','+5%','Vitesse de soin','+50%','Affinité des Ruines augmentée','+15%'],isis:['Capacité de l’Hôpital augmentée','+500','Vitesse de soin','+50%','Affinité des Ruines augmentée','+15%']},prefix:'Temple de'},
it:{questTitle:'MISSIONI DEI TEMPLI',questSub:'Accedi, scegli e avvia le missioni dei templi.',steps:[
['Apri il menu delle missioni','Tocca l’<strong>icona delle missioni del tempio</strong> sul lato sinistro della mappa per aprire il menu.'],
['Scegli un tempio e tocca GO','Seleziona un tempio disponibile, controlla la missione e tocca <strong>GO</strong> per aprirla.'],
['Scegli le opzioni della missione','Usa <strong>Free Refresh</strong> per cambiare missione. I primi 2 aggiornamenti sono gratuiti; i successivi costano Rubini.<br><br>Usa il <strong>pulsante di upgrade</strong> accanto al grado per portare la missione ad <strong>A o S</strong> e ottenere ricompense migliori.']
],buffTitle:'BUFF DEI TEMPLI',buffSub:'Ogni tempio concede un bonus stagionale specifico. Tutti aumentano anche l’Affinità delle Rovine.',buffs:{
shou:['Difesa Warrior stagionale','+15%','Affinità Rovine aumentata','+15%'],seth:['Attacco Warrior stagionale','+15%','Affinità Rovine aumentata','+15%'],nout:['Attacco Arciere stagionale','+15%','Affinità Rovine aumentata','+15%'],tefnout:['Difesa Arciere stagionale','+15%','Affinità Rovine aumentata','+15%'],geb:['Difesa Cavalleria stagionale','+15%','Affinità Rovine aumentata','+15%'],nephthys:['Attacco Cavalleria stagionale','+15%','Affinità Rovine aumentata','+15%'],sobek:['Danni alle truppe stagionali ridotti','+5%','Velocità di cura','+50%','Affinità Rovine aumentata','+15%'],isis:['Capacità Ospedale aumentata','+500','Velocità di cura','+50%','Affinità Rovine aumentata','+15%']},prefix:'Tempio di'},
de:{questTitle:'TEMPEL-AUFGABEN',questSub:'Tempelmissionen öffnen, auswählen und starten.',steps:[
['Tempel-Aufgabenmenü öffnen','Tippe links auf der Weltkarte auf das <strong>Tempel-Aufgaben-Symbol</strong>, um das Missionsmenü zu öffnen.'],
['Tempel wählen und GO drücken','Wähle einen verfügbaren Tempel, prüfe die Mission und tippe auf <strong>GO</strong>.'],
['Missionsoptionen wählen','Mit <strong>Free Refresh</strong> kannst du die Mission wechseln. Die ersten 2 Aktualisierungen sind kostenlos, danach kosten sie Rubine.<br><br>Mit der <strong>Upgrade-Schaltfläche</strong> neben dem Rang kannst du die Mission auf <strong>A oder S</strong> verbessern und bessere Belohnungen erhalten.']
],buffTitle:'TEMPEL-ATTRIBUTBUFFS',buffSub:'Jeder Tempel gewährt einen eigenen Saisonbonus. Alle Tempel erhöhen außerdem die Ruinen-Affinität.',buffs:{
shou:['Saison-Warrior-Verteidigung','+15%','Ruinen-Affinität erhöht','+15%'],seth:['Saison-Warrior-Angriff','+15%','Ruinen-Affinität erhöht','+15%'],nout:['Saison-Bogenschützen-Angriff','+15%','Ruinen-Affinität erhöht','+15%'],tefnout:['Saison-Bogenschützen-Verteidigung','+15%','Ruinen-Affinität erhöht','+15%'],geb:['Saison-Kavallerie-Verteidigung','+15%','Ruinen-Affinität erhöht','+15%'],nephthys:['Saison-Kavallerie-Angriff','+15%','Ruinen-Affinität erhöht','+15%'],sobek:['Schaden an Saisontruppen reduziert','+5%','Behandlungsgeschwindigkeit','+50%','Ruinen-Affinität erhöht','+15%'],isis:['Krankenhauskapazität erhöht','+500','Behandlungsgeschwindigkeit','+50%','Ruinen-Affinität erhöht','+15%']},prefix:'Tempel des'},
pl:{questTitle:'MISJE ŚWIĄTYŃ',questSub:'Otwieraj, wybieraj i uruchamiaj misje świątyń.',steps:[
['Otwórz menu misji świątyń','Dotknij <strong>ikony misji świątyń</strong> po lewej stronie mapy świata, aby otworzyć menu.'],
['Wybierz świątynię i naciśnij GO','Wybierz dostępną świątynię, sprawdź misję i naciśnij <strong>GO</strong>.'],
['Wybierz opcje misji','Użyj <strong>Free Refresh</strong>, aby zmienić misję. Pierwsze 2 odświeżenia są darmowe; kolejne kosztują Rubiny.<br><br>Użyj <strong>przycisku ulepszenia</strong> obok rangi misji, aby podnieść ją do <strong>A lub S</strong> i zdobyć lepsze nagrody.']
],buffTitle:'BUFFY ŚWIĄTYŃ',buffSub:'Każda świątynia zapewnia inny bonus sezonowy. Wszystkie zwiększają również Affinity Ruin.',buffs:{
shou:['Obrona sezonowych Warriorów','+15%','Zwiększone Affinity Ruin','+15%'],seth:['Atak sezonowych Warriorów','+15%','Zwiększone Affinity Ruin','+15%'],nout:['Atak sezonowych Łuczników','+15%','Zwiększone Affinity Ruin','+15%'],tefnout:['Obrona sezonowych Łuczników','+15%','Zwiększone Affinity Ruin','+15%'],geb:['Obrona sezonowej Kawalerii','+15%','Zwiększone Affinity Ruin','+15%'],nephthys:['Atak sezonowej Kawalerii','+15%','Zwiększone Affinity Ruin','+15%'],sobek:['Zmniejszone obrażenia dla wojsk sezonowych','+5%','Szybkość leczenia','+50%','Zwiększone Affinity Ruin','+15%'],isis:['Zwiększona pojemność Szpitala','+500','Szybkość leczenia','+50%','Zwiększone Affinity Ruin','+15%']},prefix:'Świątynia'},
ru:{questTitle:'ЗАДАНИЯ ХРАМОВ',questSub:'Открывай, выбирай и запускай задания храмов.',steps:[
['Открой меню заданий храмов','Нажми <strong>значок заданий храмов</strong> слева на карте мира, чтобы открыть меню.'],
['Выбери храм и нажми GO','Выбери доступный храм, проверь задание и нажми <strong>GO</strong>.'],
['Выбери параметры задания','Используй <strong>Free Refresh</strong>, чтобы сменить задание. Первые 2 обновления бесплатны, затем требуются Рубины.<br><br>Используй <strong>кнопку улучшения</strong> рядом с рангом, чтобы повысить задание до <strong>A или S</strong> и получить лучшие награды.']
],buffTitle:'БОНУСЫ ХРАМОВ',buffSub:'Каждый храм даёт особый сезонный бонус. Все храмы также повышают Affinity Руин.',buffs:{
shou:['Защита сезонных Warrior','+15%','Affinity Руин увеличена','+15%'],seth:['Атака сезонных Warrior','+15%','Affinity Руин увеличена','+15%'],nout:['Атака сезонных Лучников','+15%','Affinity Руин увеличена','+15%'],tefnout:['Защита сезонных Лучников','+15%','Affinity Руин увеличена','+15%'],geb:['Защита сезонной Кавалерии','+15%','Affinity Руин увеличена','+15%'],nephthys:['Атака сезонной Кавалерии','+15%','Affinity Руин увеличена','+15%'],sobek:['Снижение урона сезонным войскам','+5%','Скорость лечения','+50%','Affinity Руин увеличена','+15%'],isis:['Вместимость Госпиталя увеличена','+500','Скорость лечения','+50%','Affinity Руин увеличена','+15%']},prefix:'Храм'},
uk:{questTitle:'ЗАВДАННЯ ХРАМІВ',questSub:'Відкривай, обирай і запускай завдання храмів.',steps:[
['Відкрий меню завдань храмів','Натисни <strong>значок завдань храмів</strong> ліворуч на карті світу, щоб відкрити меню.'],
['Обери храм і натисни GO','Обери доступний храм, перевір завдання та натисни <strong>GO</strong>.'],
['Обери параметри завдання','Використовуй <strong>Free Refresh</strong>, щоб змінити завдання. Перші 2 оновлення безкоштовні, далі потрібні Рубіни.<br><br>Використовуй <strong>кнопку покращення</strong> біля рангу, щоб підняти завдання до <strong>A або S</strong> і отримати кращі нагороди.']
],buffTitle:'БОНУСИ ХРАМІВ',buffSub:'Кожен храм дає окремий сезонний бонус. Усі храми також підвищують Affinity Руїн.',buffs:{
shou:['Захист сезонних Warrior','+15%','Affinity Руїн збільшено','+15%'],seth:['Атака сезонних Warrior','+15%','Affinity Руїн збільшено','+15%'],nout:['Атака сезонних Лучників','+15%','Affinity Руїн збільшено','+15%'],tefnout:['Захист сезонних Лучників','+15%','Affinity Руїн збільшено','+15%'],geb:['Захист сезонної Кавалерії','+15%','Affinity Руїн збільшено','+15%'],nephthys:['Атака сезонної Кавалерії','+15%','Affinity Руїн збільшено','+15%'],sobek:['Зменшення шкоди сезонним військам','+5%','Швидкість лікування','+50%','Affinity Руїн збільшено','+15%'],isis:['Місткість Госпіталю збільшено','+500','Швидкість лікування','+50%','Affinity Руїн збільшено','+15%']},prefix:'Храм'}};
const temples=[
['shou','Shou','blue','🏺','🛡'],['seth','Seth','blue','☾','⚔'],['nout','Nout','purple','✦','🏹'],['tefnout','Tefnout','purple','🏆','🛡'],['geb','Geb','orange','◉','⚙'],['nephthys','Nephthys','orange','♨','⚔'],['sobek','Sobek','green','🛡','✚'],['isis','Isis','green','⌛','🏥']];
function lang(){const x=localStorage.getItem(K),s=document.getElementById('languageSelect')?.value,l=(document.getElementById('abyxLangCurrent')?.textContent||'').trim().toUpperCase(),m={EN:'en',FR:'fr',IT:'it',DE:'de',PL:'pl',RU:'ru',UA:'uk'};return S.includes(x)?x:S.includes(s)?s:m[l]||'en'}
function create(){const r=document.getElementById('templeInfographic');if(!r||document.getElementById('templeQuestExtra'))return;
const footer=r.querySelector('.temple-guide-footer');if(!footer)return;
footer.insertAdjacentHTML('beforebegin',`<section id="templeQuestExtra" class="temple-extra-section temple-extra-quests">
<div class="temple-extra-head"><span>☥</span><div><h3 data-x="questTitle"></h3><p data-x="questSub"></p></div></div>
<div class="temple-quest-grid">
<article class="temple-quest-card"><div class="temple-quest-num">1</div><div class="quest-visual quest-map" aria-hidden="true"><span class="qv-menu">▦</span><span>♟</span><span>⌕</span><span class="qv-active">▤</span><i>1</i></div><div class="temple-quest-copy"><h4></h4><p></p></div></article>
<article class="temple-quest-card"><div class="temple-quest-num">2</div><div class="quest-visual quest-list" aria-hidden="true"><b>RUINS MISSION!</b><div><span>Temple of Seth</span><em>GO</em></div><div><span>Temple of Shou</span><em>GO</em></div><div><span>Temple of Nephthys</span><em>GO</em></div></div><div class="temple-quest-copy"><h4></h4><p></p></div></article>
<article class="temple-quest-card"><div class="temple-quest-num">3</div><div class="quest-visual quest-options" aria-hidden="true"><b>Temple of Seth</b><div class="qv-rank">A</div><p>0 / 3000</p><div class="qv-buttons"><span>⟳ Free Refresh</span><span>Accept Mission</span></div><small>↯ Upgrade to A / S</small></div><div class="temple-quest-copy"><h4></h4><p></p></div></article>
</div></section>
<section id="templeBuffExtra" class="temple-extra-section temple-extra-buffs">
<div class="temple-extra-head"><span>✦</span><div><h3 data-x="buffTitle"></h3><p data-x="buffSub"></p></div></div>
<div class="temple-buff-grid">${temples.map(([id,n,c,a,b])=>`<article class="temple-buff-card ${c}" data-buff="${id}"><div class="temple-buff-visual"><span class="temple-avatar">${n.slice(0,1)}</span><strong>${a}</strong><i>◆</i><strong>${b}</strong></div><div class="temple-buff-copy"><h4></h4><div class="temple-buff-lines"></div></div></article>`).join('')}</div>
</section>`)}
function buffLines(a){let h='';for(let i=0;i<a.length;i+=2)h+=`<div><span>${a[i]}</span><strong>${a[i+1]}</strong></div>`;return h}
function apply(){create();const t=DATA[lang()]||DATA.en,root=document.getElementById('templeInfographic');if(!root)return;root.querySelector('[data-x="questTitle"]')?.replaceChildren(document.createTextNode(t.questTitle));root.querySelector('[data-x="questSub"]')?.replaceChildren(document.createTextNode(t.questSub));root.querySelectorAll('.temple-quest-card').forEach((c,i)=>{c.querySelector('h4').innerHTML=t.steps[i][0];c.querySelector('.temple-quest-copy p').innerHTML=t.steps[i][1]});root.querySelector('[data-x="buffTitle"]')?.replaceChildren(document.createTextNode(t.buffTitle));root.querySelector('[data-x="buffSub"]')?.replaceChildren(document.createTextNode(t.buffSub));root.querySelectorAll('.temple-buff-card').forEach(c=>{const id=c.dataset.buff,n=temples.find(x=>x[0]===id)?.[1]||id;c.querySelector('h4').textContent=`${t.prefix} ${n}`;c.querySelector('.temple-buff-lines').innerHTML=buffLines(t.buffs[id])})}
function later(){requestAnimationFrame(()=>requestAnimationFrame(apply))}
function init(){const sh=document.querySelector('#detailModal .detail-sheet');if(sh)new MutationObserver(later).observe(sh,{childList:true,subtree:true});const c=document.getElementById('abyxLangCurrent');if(c)new MutationObserver(later).observe(c,{childList:true,subtree:true,characterData:true});document.getElementById('languageSelect')?.addEventListener('change',later);document.addEventListener('click',e=>{if(e.target.closest('.abyx-lang-option,.system-card,.search-result'))later()});later()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
